# Generated by Django 4.1 on 2026-06-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_movie_actors_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
